### ISSUE TITLE
"building circuits" forever

### ISSUE THREAD

**Issue by mlee952** [Tribler/tribler.github.com#36]
I was running 6.5.2. on Win 7 Pro, 64 bit.  Tribler crashed a few times and reported "building circuits" forever on every restart.
Upgraded to 7.0.1.  "building circuits" forever.
Removed and reinstalled 7.0.1. same problem
Please help

**Comment by xoriole** [comment]
@mlee952  Thank you for reporting.
Could you provide us the logs so we know what is happening?
Logs are located in `C:\Users\<your_username>\AppData\Roaming\.Tribler\logs`

**Comment by mlee952** [comment]
do not have "AppData" folder on my computer.
I sent log files after at least 3 crashes.

**Comment by mlee952** [comment]
cannot find .tribler file

**Comment by mlee952** [comment]
Do I have to turn on Developer mode to create log file?

**Comment by xoriole** [comment]
`AppData` folder is not visible on the explorer on browsing but the path works if you paste it into the address bar. Alternatively, you could type `%AppData%` in  Windows Run command and it will open a folder with `.Tribler` in it.

About the log file, logging is enabled by default. You do not need to enable developer mode for it. However, you can also see the logs separately in the Debug Console.

**Comment by mlee952** [comment]
On Friday, February 16, 2018, 4:10:57 AM CST, Sandip Pandey <notifications@github.com> wrote:  
 
 
AppData folder is not visible on the explorer on browsing but the path works if you paste it into the address bar. Alternatively, you could type %AppData% in Windows Run command and it will open a folder with .Tribler in it.

About the log file, logging is enabled by default. You do not need to enable developer mode for it. However, you can also see the logs separately in the Debug Console.

**Comment by devos50** [comment]
Please re-open this issue on our main Tribler repository: https://github.com/tribler/tribler. This is the repository that hosts our website.
