### ISSUE TITLE
FAQ states encryption unsupported, no longer true?

### ISSUE THREAD

**Issue by hoxia** [Tribler/tribler.github.com#66]
Referring to FAQ section Supported Features, "Does Tribler support encryption?":
https://github.com/Tribler/tribler.github.com/blob/8722f9df554bd400c79fe59f24e0320a879ef31f/faq.html#L304-L311

This states quite clearly that encryption is not supported. However, encryption is mentioned frequently elsewhere, and may have been implemented since that FAQ section was (apparently) written, in 2014.
https://github.com/Tribler/tribler.github.com/commit/efe7ccf975e298b7e8d404dd76f72bc462c3fecd

This merge suggests opportunistic encryption is now supported as of 2015:
https://github.com/Tribler/tribler/pull/1388

**Comment by qstokkink** [comment]
Thanks for the report! I confirmed that we indeed still have opportunistic encryption implemented for all libtorrent versions:

https://github.com/Tribler/tribler/blob/c98871b033ac9e1ccc9cecd242734e8b9bf3e1d0/src/tribler-core/tribler_core/modules/libtorrent/download_manager.py#L181-L187
