### ISSUE TITLE
Make statistics only display integers

### ISSUE THREAD

**Issue by Shidouuu** [Tribler/tribler.github.com#72]
Self explanatory:

![image](https://user-images.githubusercontent.com/36283656/103944862-48513c80-5102-11eb-9d5a-53e9566a14ab.png)

**Comment by Shidouuu** [comment]
Thanks
![image](https://user-images.githubusercontent.com/36283656/104111011-7b82ff80-52ab-11eb-8fb7-b62fffa68f04.png)

**Comment by xoriole** [comment]
@Shidouuu Thank you for the report. The issue is not fixed yet. The statistics server is superseded by Dashboard project at https://dashboard.tribler.org which would be public after the first release.
