### ISSUE TITLE
Some documentation segments in the website are outdated

### ISSUE THREAD

**Issue by Solomon1732** [Tribler/tribler.github.com#75]
According to Tribler/tribler#5604 (opened by @devos50 ) some FAQs in the website are outdated. This seems to me to be the repo to handle such issues. Thus I thought I should link the original issue here.

**Comment by drew2a** [comment]
Related to https://github.com/Tribler/tribler/issues/5550

**Comment by Solomon1732** [comment]
The howto page has oudated screenshots:
https://www.tribler.org/howto.html

It looks like the UI changed somewhat since the time said screenshots were documented.
